import sys, os
#
#	Receives a python script file generated by jc.py and runs it. 
#
def main():

	if len(sys.argv) != 2:
		error('Invalid argument.', 1)
	try:
		module = load_file()
	except (IOError, ImportError):
		error('Unable to open file.', 2)
	except ValueError:
		error('Invalid File.', 3)

	json = module.generateInstance()
	print json

def error(msg, code):
	sys.stderr.write('Error: ' + msg + '\n')
	exit(code)

def load_file():
	filepath = sys.argv[1] 
	mod_name,file_ext = os.path.splitext(os.path.split(filepath)[-1])
	if file_ext.lower() != '.py':
		raise ValueError()
	return __import__(mod_name)

if __name__ == '__main__':
	main()